//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class access
    {
        public int id { get; set; }
        public int profileId { get; set; }
        public int menuId { get; set; }
        public byte create { get; set; }
        public byte update { get; set; }
        public byte delete { get; set; }
        public byte all { get; set; }
        public byte list { get; set; }
        public byte upload { get; set; }
        public byte admin { get; set; }
        public Nullable<byte> disabled { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual menus menus { get; set; }
        public virtual profiles profiles { get; set; }
    }
}
