//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public decimal dato_id { get; set; }
        public decimal dato_imagen_id { get; set; }
        public decimal dato_campo_id { get; set; }
        public Nullable<decimal> dato_numero { get; set; }
        public string dato_texto { get; set; }
        public string dato_memo { get; set; }
        public string dato_fecha { get; set; }
        public int dato_lote_id { get; set; }
        public string dato_indice1 { get; set; }
        public string dato_indice2 { get; set; }
        public string dato_indice3 { get; set; }
        public string dato_indice4 { get; set; }
        public Nullable<decimal> dato_paginas { get; set; }
        public Nullable<System.DateTime> dato_fecha_registro { get; set; }
        public string dato_tamano { get; set; }
        public string dato_extension { get; set; }
        public Nullable<bool> estado_expediente { get; set; }
        public Nullable<System.DateTime> fecha_update_expediente { get; set; }
        public Nullable<bool> estado_carpeta { get; set; }
        public Nullable<System.DateTime> fecha_update_carpeta { get; set; }
        public Nullable<bool> estado_cuaderno { get; set; }
        public Nullable<System.DateTime> fecha_update_cuaderno { get; set; }
        public Nullable<bool> estado_imagen { get; set; }
        public Nullable<System.DateTime> fecha_update_imagen { get; set; }
    }
}
