//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALIDAD
    {
        public decimal calidad_id { get; set; }
        public Nullable<int> calidad_Porcentajelotes { get; set; }
        public Nullable<int> calidad_PorcentajeError { get; set; }
        public Nullable<decimal> calidad_CantidadRegistrosbase { get; set; }
        public Nullable<decimal> calidad_CantidadErrores { get; set; }
        public Nullable<int> calidad_uno { get; set; }
        public Nullable<int> calidad_dos { get; set; }
        public string calidad_indice0 { get; set; }
        public string calidad_indice1 { get; set; }
    }
}
