//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALIDAD_ANM
    {
        public decimal ID { get; set; }
        public decimal CALIDAD_ID { get; set; }
        public int ITEM { get; set; }
        public int NA { get; set; }
        public int CUMPLE { get; set; }
        public int NOCUMPLE { get; set; }
        public string OBSERVACIONES { get; set; }
        public string FECHA { get; set; }
        public string USUARIO { get; set; }
    }
}
