//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campos()
        {
            this.camposxtipodoc = new HashSet<camposxtipodoc>();
            this.datos = new HashSet<datos>();
        }
    
        public decimal campo_id { get; set; }
        public string campo_nombre { get; set; }
        public string campo_etiqueta { get; set; }
        public string campo_tipo { get; set; }
        public Nullable<decimal> campo_lista_id { get; set; }
        public int campo_esrequerido { get; set; }
        public decimal campodepende_campo_id { get; set; }
        public string campodepende_campovalorloactiva { get; set; }
        public decimal campo_ancho { get; set; }
        public decimal campo_alto { get; set; }
        public decimal campo_contador_portipodoc { get; set; }
        public string campo_asociado_nombre { get; set; }
        public string campo_fijo_valor { get; set; }
        public string campo_expresion_cadenaexp { get; set; }
        public decimal campo_contador_localacarpeta { get; set; }
    
        public virtual listas listas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<camposxtipodoc> camposxtipodoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datos> datos { get; set; }
    }
}
