//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPOSPROCESOSTIPOSDEDOCUMENTO
    {
        public decimal campoprocesotipo_id { get; set; }
        public decimal campoprocesotipo_proceso_id { get; set; }
        public decimal campoprocesotipo_campotipo_id { get; set; }
        public decimal campoprocesotipo_ordenz { get; set; }
        public Nullable<decimal> campoprocesotipo_modificable { get; set; }
        public decimal campoprocesotipo_insertarendatos { get; set; }
        public decimal campoprocesotipo_endatos { get; set; }
        public decimal campoprocesotipo_envariable { get; set; }
    }
}
