//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOSRAD
    {
        public decimal datorad_id { get; set; }
        public decimal datorad_radicacion_id { get; set; }
        public decimal datorad_campo_id { get; set; }
        public Nullable<decimal> datorad_numero { get; set; }
        public string datorad_texto { get; set; }
        public string datorad_memo { get; set; }
        public string datorad_fecha { get; set; }
    }
}
