//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datos_2
    {
        public decimal dato_id { get; set; }
        public decimal dato_imagen_id { get; set; }
        public decimal dato_campo_id { get; set; }
        public Nullable<decimal> dato_numero { get; set; }
        public string dato_texto { get; set; }
        public string dato_memo { get; set; }
        public string dato_fecha { get; set; }
        public decimal dato_Iguales { get; set; }
        public string dato_digitado1 { get; set; }
        public string dato_digitado2 { get; set; }
        public string dato_nuevoValor { get; set; }
        public int dato_error { get; set; }
        public string dato_descripcionError { get; set; }
    }
}
