//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class featureServicio
    {
        public int id { get; set; }
        public int servicioId { get; set; }
        public int feaureId { get; set; }
    
        public virtual features features { get; set; }
        public virtual servicios servicios { get; set; }
    }
}
