//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public imagenes()
        {
            this.datos = new HashSet<datos>();
        }
    
        public decimal imagen_id { get; set; }
        public Nullable<decimal> imagen_orden { get; set; }
        public string imagen_nombre { get; set; }
        public Nullable<decimal> imagen_lote_id { get; set; }
        public Nullable<decimal> imagen_tipodoc_id { get; set; }
        public Nullable<int> imagen_indice { get; set; }
        public int imagen_estado { get; set; }
        public Nullable<System.DateTime> imagen_fechaindexa { get; set; }
        public Nullable<decimal> imagen_usuarioindexa_id { get; set; }
        public decimal imagen_tipodoc_id2 { get; set; }
        public decimal imagen_tipodoc_id3 { get; set; }
        public Nullable<System.DateTime> imagen_fechaReindexa { get; set; }
        public Nullable<decimal> imagen_usuarioReindexa_id { get; set; }
        public Nullable<System.DateTime> imagen_fechaVerifica { get; set; }
        public Nullable<decimal> imagen_usuarioVerifica_id { get; set; }
        public Nullable<System.DateTime> imagen_fechaCalidad { get; set; }
        public Nullable<decimal> imagen_usuarioCalidad_id { get; set; }
        public Nullable<System.DateTime> imagen_fechaAuditoria { get; set; }
        public Nullable<decimal> imagen_usuarioAuditoria_id { get; set; }
        public string imagen_marcaAuditoria { get; set; }
        public string imagen_obsAuditoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datos> datos { get; set; }
        public virtual lotes lotes { get; set; }
    }
}
