//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_error
    {
        public int log_id { get; set; }
        public string message { get; set; }
        public string StackTrace { get; set; }
        public System.DateTime date_insert { get; set; }
        public int type { get; set; }
    }
}
