//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lotes()
        {
            this.ArchivosZip = new HashSet<ArchivosZip>();
            this.imagenes = new HashSet<imagenes>();
        }
    
        public decimal lote_id { get; set; }
        public string lote_nombre { get; set; }
        public decimal lote_serie_id { get; set; }
        public int lote_estado { get; set; }
        public System.DateTime lote_fechaimporta { get; set; }
        public decimal lote_usuarioimporta_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivosZip> ArchivosZip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imagenes> imagenes { get; set; }
        public virtual series series { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
