//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SID_PROTOCOL2Entities : DbContext
    {
        public SID_PROTOCOL2Entities()
            : base("name=SID_PROTOCOL2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<initialDate> initialDate { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<ArchivosZip> ArchivosZip { get; set; }
        public virtual DbSet<auditorias> auditorias { get; set; }
        public virtual DbSet<CALIDAD> CALIDAD { get; set; }
        public virtual DbSet<CALIDAD_ANM> CALIDAD_ANM { get; set; }
        public virtual DbSet<CALIDADLOTES> CALIDADLOTES { get; set; }
        public virtual DbSet<campos> campos { get; set; }
        public virtual DbSet<CAMPOSPROCESOSTIPOSDEDOCUMENTO> CAMPOSPROCESOSTIPOSDEDOCUMENTO { get; set; }
        public virtual DbSet<camposxtipodoc> camposxtipodoc { get; set; }
        public virtual DbSet<datos> datos { get; set; }
        public virtual DbSet<datos_2> datos_2 { get; set; }
        public virtual DbSet<datos_finales> datos_finales { get; set; }
        public virtual DbSet<DATOSRAD> DATOSRAD { get; set; }
        public virtual DbSet<Despachos> Despachos { get; set; }
        public virtual DbSet<imagenes> imagenes { get; set; }
        public virtual DbSet<listas> listas { get; set; }
        public virtual DbSet<lotes> lotes { get; set; }
        public virtual DbSet<PERSONAS_NOMINAS> PERSONAS_NOMINAS { get; set; }
        public virtual DbSet<PROCESOS> PROCESOS { get; set; }
        public virtual DbSet<RAD_ALIST> RAD_ALIST { get; set; }
        public virtual DbSet<RefreshToken> RefreshToken { get; set; }
        public virtual DbSet<series> series { get; set; }
        public virtual DbSet<tiposdedocumentos> tiposdedocumentos { get; set; }
        public virtual DbSet<TIPOSDELOTES> TIPOSDELOTES { get; set; }
        public virtual DbSet<TQM_LOCK> TQM_LOCK { get; set; }
        public virtual DbSet<TQM_LOCK_CALIDAD> TQM_LOCK_CALIDAD { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<valoreslistas> valoreslistas { get; set; }
        public virtual DbSet<Folder> Folder { get; set; }
        public virtual DbSet<parametersApi> parametersApi { get; set; }
        public virtual DbSet<urlApiI> urlApiI { get; set; }
        public virtual DbSet<EQUIVALENCIAS> EQUIVALENCIAS { get; set; }
        public virtual DbSet<errores> errores { get; set; }
        public virtual DbSet<DB_Errors> DB_Errors { get; set; }
        public virtual DbSet<log_error> log_error { get; set; }
    }
}
