//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class solucionesIntegrales58Entities : DbContext
    {
        public solucionesIntegrales58Entities()
            : base("name=solucionesIntegrales58Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<documents> documents { get; set; }
        public virtual DbSet<features> features { get; set; }
        public virtual DbSet<access> access { get; set; }
        public virtual DbSet<accessSubService> accessSubService { get; set; }
        public virtual DbSet<categorys> categorys { get; set; }
        public virtual DbSet<contactanos> contactanos { get; set; }
        public virtual DbSet<costoXPeriodo> costoXPeriodo { get; set; }
        public virtual DbSet<ctasCorriente> ctasCorriente { get; set; }
        public virtual DbSet<documentServicio> documentServicio { get; set; }
        public virtual DbSet<featureServicio> featureServicio { get; set; }
        public virtual DbSet<grupos> grupos { get; set; }
        public virtual DbSet<grupoServicio> grupoServicio { get; set; }
        public virtual DbSet<identificationTypes> identificationTypes { get; set; }
        public virtual DbSet<menus> menus { get; set; }
        public virtual DbSet<pagosOnLineEstados> pagosOnLineEstados { get; set; }
        public virtual DbSet<parameters> parameters { get; set; }
        public virtual DbSet<parents> parents { get; set; }
        public virtual DbSet<prioritys> prioritys { get; set; }
        public virtual DbSet<profiles> profiles { get; set; }
        public virtual DbSet<servicioAdquirido> servicioAdquirido { get; set; }
        public virtual DbSet<servicioAdquiridoBeneficiarios> servicioAdquiridoBeneficiarios { get; set; }
        public virtual DbSet<servicioAdquiridoBeneficiariosExequialDelete> servicioAdquiridoBeneficiariosExequialDelete { get; set; }
        public virtual DbSet<servicioAuxExequialDelete> servicioAuxExequialDelete { get; set; }
        public virtual DbSet<servicioAuxExequialDetalleDelete> servicioAuxExequialDetalleDelete { get; set; }
        public virtual DbSet<servicioAuxPlanCigueniaDelete> servicioAuxPlanCigueniaDelete { get; set; }
        public virtual DbSet<servicioAuxPlanCigueniaDetalleDelete> servicioAuxPlanCigueniaDetalleDelete { get; set; }
        public virtual DbSet<servicioAuxSocialDesempleoDelete> servicioAuxSocialDesempleoDelete { get; set; }
        public virtual DbSet<servicioAuxSocialDesempleoDetalleDelete> servicioAuxSocialDesempleoDetalleDelete { get; set; }
        public virtual DbSet<servicioJuridicoDelete> servicioJuridicoDelete { get; set; }
        public virtual DbSet<servicioJuridicoDetalleDelete> servicioJuridicoDetalleDelete { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<serviciosSolicitados> serviciosSolicitados { get; set; }
        public virtual DbSet<serviciosSolicitadosClasificacion> serviciosSolicitadosClasificacion { get; set; }
        public virtual DbSet<serviciosSolicitadosDocumentos> serviciosSolicitadosDocumentos { get; set; }
        public virtual DbSet<sliders> sliders { get; set; }
        public virtual DbSet<stateService> stateService { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ubicanos> ubicanos { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<userTypes> userTypes { get; set; }
        public virtual DbSet<userTypesGrupos> userTypesGrupos { get; set; }
        public virtual DbSet<contrato> contrato { get; set; }
        public virtual DbSet<parametrosGrales> parametrosGrales { get; set; }
        public virtual DbSet<prioridades> prioridades { get; set; }
        public virtual DbSet<smtp> smtp { get; set; }
        public virtual DbSet<pagosOnLine> pagosOnLine { get; set; }
        public virtual DbSet<initialDate> initialDate { get; set; }
        public virtual DbSet<parametersPbx> parametersPbx { get; set; }
        public virtual DbSet<tokenUri> tokenUri { get; set; }
        public virtual DbSet<pay> pay { get; set; }
        public virtual DbSet<payDetail> payDetail { get; set; }
        public virtual DbSet<urlApiItbx> urlApiItbx { get; set; }
        public virtual DbSet<registroPbx> registroPbx { get; set; }
        public virtual DbSet<logs> logs { get; set; }
        public virtual DbSet<serviciosToSave> serviciosToSave { get; set; }
    }
}
