//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payDetail
    {
        public int id { get; set; }
        public string typeDocument { get; set; }
        public string nroDocument { get; set; }
        public int desconocido1 { get; set; }
        public string desconocido2 { get; set; }
        public int desconocido3 { get; set; }
        public int desconocido4 { get; set; }
        public System.DateTime date1 { get; set; }
        public int desconocido5 { get; set; }
        public string desconocido6 { get; set; }
        public string desconocido7 { get; set; }
        public System.DateTime date2 { get; set; }
        public string desconocido8 { get; set; }
        public string desconocido9 { get; set; }
        public int desconocido10 { get; set; }
        public string desconocido11 { get; set; }
        public string desconocido12 { get; set; }
        public string desconocido13 { get; set; }
        public string desconocido14 { get; set; }
        public string desconocido15 { get; set; }
    }
}
