//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS_NOMINAS
    {
        public decimal ID { get; set; }
        public decimal IDENT { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
    }
}
