//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAD_ALIST
    {
        public decimal radicacion_id { get; set; }
        public string radicacion_lote { get; set; }
        public string radicacion_fecha { get; set; }
        public string radicacion_hora { get; set; }
        public string radicacion_usuario { get; set; }
        public string radicacion_estado { get; set; }
        public Nullable<decimal> alista_imagenes { get; set; }
        public string alista_fecha { get; set; }
        public string alista_hora { get; set; }
        public string alista_usuario { get; set; }
        public string alista_estado { get; set; }
        public string digitalizo_fecha { get; set; }
        public string digitalizo_hora { get; set; }
        public string digitalizo_usuario { get; set; }
        public string digitalizo_estado { get; set; }
        public decimal digitalizo_imagenes { get; set; }
        public string verifico_fecha { get; set; }
        public string verifico_hora { get; set; }
        public string verifico_usuario { get; set; }
        public string verifico_estado { get; set; }
        public Nullable<decimal> verifico_imagenes { get; set; }
        public string verifico_observaciones { get; set; }
        public string importo_fecha { get; set; }
        public string importo_hora { get; set; }
        public string importo_usuario { get; set; }
        public string importo_estado { get; set; }
        public decimal radicacion_tipolote_id { get; set; }
        public decimal radicacion_tipodoc_id { get; set; }
        public string radicacion_camposvariables { get; set; }
        public string alista_camposvariables { get; set; }
    }
}
