//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicioAdquiridoBeneficiariosExequialDelete
    {
        public int id { get; set; }
        public int servAdqContratoId { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public int identificationTypesId { get; set; }
        public long nroDocumento { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    }
}
