//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviciosSolicitados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public serviciosSolicitados()
        {
            this.serviciosSolicitadosDocumentos = new HashSet<serviciosSolicitadosDocumentos>();
        }
    
        public int id { get; set; }
        public int userId { get; set; }
        public int gruposId { get; set; }
        public int servicioId { get; set; }
        public string observation { get; set; }
        public int estado { get; set; }
        public Nullable<int> serviciosSolicitadosClasificacionId { get; set; }
        public int userIdcreatedAt { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<int> userIdupdateAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
    
        public virtual grupos grupos { get; set; }
        public virtual servicios servicios { get; set; }
        public virtual stateService stateService { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviciosSolicitadosDocumentos> serviciosSolicitadosDocumentos { get; set; }
    }
}
