//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviciosToSave
    {
        public int id { get; set; }
        public string description { get; set; }
        public bool estado { get; set; }
        public bool saveRegisters { get; set; }
        public int codigo { get; set; }
        public System.DateTime createdAt { get; set; }
    }
}
