//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicioAdquiridoBeneficiarios
    {
        public int id { get; set; }
        public string parentesco { get; set; }
        public string completeName { get; set; }
        public int edad { get; set; }
        public int servicioAdquiridoId { get; set; }
        public int servicioId { get; set; }
        public int userIdcreatedAt { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<int> userIdupdatedAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual servicios servicios { get; set; }
    }
}
