//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicios()
        {
            this.featureServicio = new HashSet<featureServicio>();
            this.grupoServicio = new HashSet<grupoServicio>();
            this.servicioAdquiridoBeneficiarios = new HashSet<servicioAdquiridoBeneficiarios>();
            this.serviciosSolicitados = new HashSet<serviciosSolicitados>();
            this.serviciosSolicitadosClasificacion = new HashSet<serviciosSolicitadosClasificacion>();
            this.serviciosSolicitadosDocumentos = new HashSet<serviciosSolicitadosDocumentos>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string descripcionCompleta { get; set; }
        public string codServicio { get; set; }
        public string url { get; set; }
        public string icon { get; set; }
        public int orderAsc { get; set; }
        public bool hasBeneficiarios { get; set; }
        public bool validateCantPeticiones { get; set; }
        public int cantidadvalidateCantPeticiones { get; set; }
        public bool state { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<featureServicio> featureServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupoServicio> grupoServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicioAdquiridoBeneficiarios> servicioAdquiridoBeneficiarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviciosSolicitados> serviciosSolicitados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviciosSolicitadosClasificacion> serviciosSolicitadosClasificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviciosSolicitadosDocumentos> serviciosSolicitadosDocumentos { get; set; }
    }
}
