//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicioAdquirido
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int grupoId { get; set; }
        public bool estado { get; set; }
        public string urlFirmaTmp { get; set; }
        public string urlFirmaFinal { get; set; }
        public string contratoUrl { get; set; }
        public bool terminosCondiciones { get; set; }
        public long nroContrato { get; set; }
        public bool payNomina { get; set; }
        public string pin { get; set; }
        public string beneficiariosTmp { get; set; }
        public int userIdcreatedAt { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<int> userIdupdatedAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual grupos grupos { get; set; }
        public virtual users users { get; set; }
    }
}
