//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smtp
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string pass { get; set; }
        public bool enable_ssl { get; set; }
        public string host { get; set; }
        public int port { get; set; }
    }
}
