//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stateService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stateService()
        {
            this.servicioAuxExequialDelete = new HashSet<servicioAuxExequialDelete>();
            this.servicioAuxPlanCigueniaDelete = new HashSet<servicioAuxPlanCigueniaDelete>();
            this.servicioAuxSocialDesempleoDelete = new HashSet<servicioAuxSocialDesempleoDelete>();
            this.servicioJuridicoDelete = new HashSet<servicioJuridicoDelete>();
            this.serviciosSolicitados = new HashSet<serviciosSolicitados>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public string observacion { get; set; }
        public bool state { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicioAuxExequialDelete> servicioAuxExequialDelete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicioAuxPlanCigueniaDelete> servicioAuxPlanCigueniaDelete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicioAuxSocialDesempleoDelete> servicioAuxSocialDesempleoDelete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicioJuridicoDelete> servicioJuridicoDelete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviciosSolicitados> serviciosSolicitados { get; set; }
    }
}
