//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOSDELOTES
    {
        public decimal tipolote_id { get; set; }
        public string tipolote_nombre { get; set; }
        public decimal tipolote_proceso_id_radicacion { get; set; }
        public decimal tipolote_siradicacion { get; set; }
        public decimal tipolote_sialistamiento { get; set; }
        public decimal tipolote_sidigitalizacion { get; set; }
        public decimal tipolote_sivalidacionimagenes { get; set; }
        public decimal tipolote_proceso_id_indexacion { get; set; }
        public decimal tipolote_siindexacion { get; set; }
        public decimal tipolote_proceso_id_reindexacion { get; set; }
        public decimal tipolote_sireindexacion { get; set; }
        public decimal tipolote_siverificacion { get; set; }
        public decimal tipolote_sicontrolcalidad1 { get; set; }
        public decimal tipolote_sicontrolcalidad2 { get; set; }
        public decimal tipolote_sientrega { get; set; }
        public string tipolote_xml { get; set; }
        public decimal tipolote_proceso_id_alistamiento { get; set; }
        public decimal tipolote_repositorio_id { get; set; }
    }
}
