//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.servicioAdquirido = new HashSet<servicioAdquirido>();
            this.serviciosSolicitados = new HashSet<serviciosSolicitados>();
        }
    
        public int id { get; set; }
        public string usrEmail { get; set; }
        public string usrEmailAlternative { get; set; }
        public string usrPassword { get; set; }
        public string usrNames { get; set; }
        public string usrLastNames { get; set; }
        public int identificationTypeId { get; set; }
        public int userTypesId { get; set; }
        public long usrCedula { get; set; }
        public string usrNroCelular { get; set; }
        public string usrTelefonoFijo { get; set; }
        public string usrDireccion { get; set; }
        public bool usrStatus { get; set; }
        public int usrOrigen { get; set; }
        public System.DateTime lastLogin { get; set; }
        public int profileId { get; set; }
        public bool hasGeolocation { get; set; }
        public Nullable<double> usrLat { get; set; }
        public Nullable<double> usrlng { get; set; }
        public bool usrTerminosCondiciones { get; set; }
        public System.DateTime lastDateLogin { get; set; }
        public string ip { get; set; }
        public string operativeSystem { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        public virtual identificationTypes identificationTypes { get; set; }
        public virtual profiles profiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicioAdquirido> servicioAdquirido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviciosSolicitados> serviciosSolicitados { get; set; }
    }
}
