//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivosZip
    {
        public int IdArchivosZip { get; set; }
        public decimal IdLote { get; set; }
        public string NombreInstancia { get; set; }
        public string NombreCuaderno { get; set; }
        public string NombreArchivo { get; set; }
        public string TipoArchivo { get; set; }
    
        public virtual lotes lotes { get; set; }
    }
}
