//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditorias
    {
        public decimal auditoria_id { get; set; }
        public string auditoria_accion { get; set; }
        public System.DateTime auditoria_fecha { get; set; }
        public decimal auditoria_usuario_id { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
