//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Errors
    {
        public int ErrorID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ErrorNumber { get; set; }
        public Nullable<int> ErrorState { get; set; }
        public Nullable<int> ErrorSeverity { get; set; }
        public Nullable<int> ErrorLine { get; set; }
        public string ErrorProcedure { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> ErrorDateTime { get; set; }
    }
}
