//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equivalencias_Integrador
    {
        public int id { get; set; }
        public string Despacho { get; set; }
        public string Serie_Subserie { get; set; }
        public string IdArea { get; set; }
        public string IdCiudad { get; set; }
        public string IdUsuario { get; set; }
        public string IdTrd { get; set; }
        public string IdVersionTrd { get; set; }
    }
}
