//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equivalencias_TiposDocumentales
    {
        public int Id { get; set; }
        public string Serie_Subserie { get; set; }
        public string ValorLista_Valor { get; set; }
        public string IdTipoDocumental { get; set; }
    }
}
