//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log1
    {
        public int id { get; set; }
        public string despacho { get; set; }
        public string idExpediente { get; set; }
        public string cuaderno { get; set; }
        public string instancia { get; set; }
        public string archivo { get; set; }
        public bool estado { get; set; }
        public string observacion { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    }
}
