//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESOS
    {
        public decimal proceso_id { get; set; }
        public string proceso_nombre { get; set; }
        public string proceso_descripcion { get; set; }
        public decimal proceso_unidad_id { get; set; }
        public string proceso_multiple { get; set; }
        public string proceso_nombresdocuanexos { get; set; }
    }
}
