//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiposdedocumentos
    {
        public decimal tipodoc_id { get; set; }
        public string tipodoc_nombre { get; set; }
        public string tipodedocumento_tipo { get; set; }
        public decimal tipodedocumento_archivosoporte { get; set; }
        public string tipodedocumento_nombreraizlote { get; set; }
        public decimal tipodedocumento_numerolote { get; set; }
        public decimal tipodedocumento_selcarpetaimag { get; set; }
        public decimal tipodedocumento_nuevoasumvalor { get; set; }
        public decimal tipodedocumento_senumeranfolio { get; set; }
        public decimal tipodedocumento_camid_campnfol { get; set; }
        public decimal tipodedocumento_posxnumfolio { get; set; }
        public decimal tipodedocumento_posynumfolio { get; set; }
        public string tipodedocumento_comotesauriza { get; set; }
        public decimal tipodedocumento_diccionario_id { get; set; }
        public decimal tipodedocumento_aceptanotas { get; set; }
        public decimal tipodedocumento_aceptamarcas { get; set; }
        public decimal tipodedocumento_serie_id { get; set; }
        public string tipodedocumento_tradicion { get; set; }
        public string tipodedocumento_valorprimario { get; set; }
        public string tipodedocumento_valorsecundari { get; set; }
        public string tipodedocumento_patronnomdoc { get; set; }
        public decimal tipodedocumento_cpid_creabanen { get; set; }
        public string tipodedocumento_impretq_campos { get; set; }
        public string tipodedocumento_impretq_archi { get; set; }
        public decimal tipodedocumento_cierracarpeta { get; set; }
        public decimal tipodedocumento_iduni_campo_id { get; set; }
        public decimal tipodedocumento_siocr { get; set; }
        public decimal tipodedocumento_siocr_enlinea { get; set; }
        public decimal campo_id_siocr { get; set; }
        public decimal tipodedocumento_sibcr { get; set; }
        public decimal tipodedocumento_sibcr_enlinea { get; set; }
        public string tipodedocumento_sibcr_estandar { get; set; }
        public decimal campo_id_sibcr { get; set; }
        public decimal tipodedocumento_sifirmadigital { get; set; }
        public decimal campo_id_sifirma { get; set; }
        public decimal tipodedoc_sifirmadigitalglobal { get; set; }
        public Nullable<short> tipodedocumento_sisubdocumentos { get; set; }
        public decimal tipodedocumento_sisellodetiempo { get; set; }
        public decimal campo_id_sisellodetiempo { get; set; }
        public decimal tipodedocumento_sifirmaelectronica { get; set; }
        public decimal campo_id_sifirmaelectronica { get; set; }
        public string tipodedocumento_sifedetalle { get; set; }
    }
}
