//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class valoreslistas
    {
        public decimal valorlista_id { get; set; }
        public string valorlista_valor { get; set; }
        public int valorlista_orden { get; set; }
        public decimal valorlista_lista_id { get; set; }
        public string valorlista_valor02 { get; set; }
    
        public virtual listas listas { get; set; }
    }
}
